version: "3.7"

services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uppraisal
    ports:
      - "3000:3000"
    networks:
      - web

volumes:
  node_modules:

networks:
  web:
    external: true