import type { Metadata } from "next"
import { Poppins } from "next/font/google"
import "./globals.css"
import clsx from 'clsx'
import '../styles/tailwind.css'


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
})

export const metadata: Metadata = {
  title: "Uppraisal",
  description: "Share your creations with the world",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={clsx('antialiased', poppins.variable)}>
      <body>{children}</body>
    </html>
  )
}

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Poppins } from "next/font/google"
import Header from "./components/header";
import FooterSection from "./components/footer";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} bg-white  antialiased`}
      >
        <div>
          <Header />
          <main>{children}</main>
          <FooterSection />
        </div>
      </body>
    </html>
  );
}
